global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cadastroapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadastroapi:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
